from javax.swing import JCheckBox
from javax.swing import BoxLayout
from javax.swing import JButton
from javax.swing import ButtonGroup
from javax.swing import JComboBox
from javax.swing import JRadioButton
from javax.swing import JList
from javax.swing import JLabel
from javax.swing import JTextArea
from javax.swing import JTextField
from javax.swing import JLabel
from java.awt import GridLayout
from java.awt import GridBagLayout
from java.awt import GridBagConstraints
from java.awt import Component
from javax.swing import JPanel
from javax.swing import JScrollPane
from javax.swing import JFileChooser
from javax.swing.filechooser import FileNameExtensionFilter

from org.sleuthkit.autopsy.ingest import IngestModuleIngestJobSettings
from org.sleuthkit.autopsy.ingest import IngestModuleIngestJobSettingsPanel

from package.utils import Utils

#https://github.com/HienTH/autopsy/blob/master/pythonExamples/fileIngestModuleWithGui.py    
class ProjectIngestSettingsPanelSettings(IngestModuleIngestJobSettings):
    serialVersionUID = 1L

    def __init__(self):
        self.flag = False

    def getVersionNumber(self):
        return serialVersionUID

    # TODO: Define getters and settings for data you want to store from UI
    def getFlag(self):
        return self.flag

    def setFlag(self, flag):
        self.flag = flag

class ProjectIngestSettingsPanel(IngestModuleIngestJobSettingsPanel):
    def __init__(self, settings):
        self.local_settings = settings
        self.initComponents()
        self.customizeComponents()

        

    # def event(self, event):
    #     self.local_settings.setSetting('adb', 'true' if self.adb.isSelected() else 'false')
    #     #self.local_settings.setSetting('clean_temp', 'true' if self.clean_temp.isSelected() else 'false')
    #     self.local_settings.setSetting('old_report', 'true' if self.json_reports.isSelected() else 'false')
    #     # self.local_settings.setSetting('app', self.app.getSelectedItem().split(' (')[0].lower())

    def initComponents(self):
        self.apps_checkboxes_list = []

        self.setLayout(BoxLayout(self, BoxLayout.PAGE_AXIS))
        
        # title 
        self.p_title = createPanel()
        self.lb_title = JLabel("Android Forensics")
        self.p_title.add(self.lb_title)
        self.add(self.p_title)
        # end of title
        
        
        # info menu
        self.p_info = createPanel()
        self.lb_info = JLabel("")
        self.lb_info2 = JLabel("")
        self.p_info.add(self.lb_info)
        self.p_info.add(self.lb_info2)
        
       
        self.add(self.p_info)

        # end of info menu

        # method menu

        self.p_method = createPanel()
        self.bg_method = ButtonGroup()
        self.rb_selectedDatasouce = createRadioButton("Analyse selected datasource", "method_datasource", self.onMethodChange)
        self.rb_importReportFile = createRadioButton("Import previous generated report file","method_importfile" ,self.onMethodChange)
        self.rb_liveExtraction = createRadioButton("Live extraction with ADB","method_adb", self.onMethodChange)
        self.rb_selectedDatasouce.setSelected(True)

        self.bg_method.add(self.rb_selectedDatasouce)
        self.bg_method.add(self.rb_importReportFile)
        self.bg_method.add(self.rb_liveExtraction)

        self.p_method.add(JLabel("Analsis method"))
        self.p_method.add(self.rb_selectedDatasouce)
        self.p_method.add(self.rb_importReportFile)
        self.p_method.add(self.rb_liveExtraction)
        self.add(self.p_method)

        # end of method menu


        #app checkboxes menu
        self.p_apps = createPanel()
        
        for app, app_id in Utils.get_all_packages().items():
            
            checkbox = addApplicationCheckbox(app, app_id, self.getSelectedApps)
            self.add(checkbox)
            self.apps_checkboxes_list.append(checkbox)
            self.p_apps.add(checkbox)

        
        self.add(self.p_apps)
        # end of checkboxes menu

        

    def customizeComponents(self):

        self.local_settings.setSetting("method", "method_adb")
        # self.local_settings.setSetting("apps", self.getSelectedApps())
    
    def onMethodChange(self, event):
        self.method = self.bg_method.getSelection().getActionCommand()
        self.local_settings.setSetting("method", self.method)

        if self.method == "method_datasource":
            self.lb_info.setText("This method is used when there is no data source but you have the device.")
            self.lb_info2.setText("It will extract the content of the selected applications from the device, analyze and index the forensic artifacts.")
            self.toggleCheckboxes(False)
            

        elif self.method == "method_importfile":
        
            self.lb_info.setText("This method is used when you already have a report in json format previously generated by the application.")
            self.lb_info2.setText("It will analyze the report previously added to the data source and index the forensic artifacts.")
            self.toggleCheckboxes(False)
    
        elif self.method == "method_adb":
            self.lb_info.setText("This method is used when the application data has already been collected.")
            self.lb_info2.setText("It will analyze the data source previously added to the data source and index the forensic artifacts.")
            self.toggleCheckboxes(True)

        # self.local_settings.setSetting("apps", self.getSelectedApps())
        

    def getSettings(self):
        return self.local_settings
    
    def getMethod(self):
        return self.bg_method.getSelection().getActionCommand()
    
    def getSelectedApps(self, event):
        selected_apps = ""
        
        for cb_app in self.apps_checkboxes_list:
            if cb_app.isSelected():
                selected_apps+= cb_app.getActionCommand()+";"
        
        selected_apps = selected_apps[:-1]
        self.local_settings.setSetting("apps", selected_apps)
        # return selected_apps


    
    def toggleCheckboxes(self, visible):
        for cb_app in self.apps_checkboxes_list:
            cb_app.setVisible(visible)


def createPanel():
    panel = JPanel()
    panel.setLayout(BoxLayout(panel, BoxLayout.PAGE_AXIS))
    panel.setAlignmentX(Component.LEFT_ALIGNMENT)
    return panel


def addApplicationCheckbox(app, app_id, ap):
        checkbox = JCheckBox("{} ({})".format(app.capitalize(), app_id), actionPerformed= ap)
        checkbox.setActionCommand(app)
        checkbox.setSelected(True)
        checkbox.setVisible(False)
        checkbox.setActionCommand(app_id)
        
        return checkbox


def createRadioButton(name, ac, ap):
    button = JRadioButton(name, actionPerformed= ap)
    button.setActionCommand(ac)
    return button   

class ProjectReportSettingsPanel(JPanel):
    def __init__(self):
        pass